### ISSUE TITLE
[Bug]: CelesteNet Players are able to push down factoryhelper buttons

### ISSUE THREAD

**Issue by Catandcomparator** [CommunalHelper/FactoryHelper#2]
### Before You Report

- [X] My mods and Everest install are up to date.
- [ ] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 11

### Bug Description

If playing on CelesteNet, and in a map with FactoryHelper buttons, if another player stands on said buttons, then they get activated on both player's ends. Here's a video showing the issue. https://youtu.be/IiTLdmSZHNI

I expected for other players to not be able to interact with the buttons on my end.

### Steps to Reproduce

Step 1. Join a factoryhelper map on celestenet
Step 2. Have other player stand on factoryhelper button
Step 3. See the object connected to factoryhelper button get activated

**Comment by bigkahuna443** [comment]
Issue is caused by CelesteNet ghosts being being handled as `Actors` with collision. Behavior may or may not be changed by the CN team, no plans to address this in Factory Helper for now.
